name: Postman Run

on:
  push:
    branches: "main" 
  pull_request:
    branches: "main" 

  workflow_dispatch:

jobs:
  run-postman-test:
    runs-on: ubuntu-latest

    steps:
      # - name: Repository checkout
      - uses: actions/checkout@v4

      # - name: Setup Node
      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install newman
        run: npm install -g newman

      - name: Run postman files on newman
        run: newman run postman_tests/Books.postman_collection.json -e postman_tests/test.postman_environment.json